spring.application.name=mi-web-app

# =========================
#  DATABASE (MySQL)
# =========================
spring.datasource.url=jdbc:mysql://localhost:3307/db_tickets_disanta?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
#  JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# (Opcional) evita warning de Open Session in View
spring.jpa.open-in-view=false

# (Opcional) logs para ver lo que hace Hibernate con el esquema
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace
